apiVersion: v1
kind: Secret
metadata:
  name: gitlab
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiZ2l0bGFiK2RlcGxveS10b2tlbi0yMjU1MzI0IiwKICAgICAgICAgICAgInBhc3N3b3JkIjoidlVra2pZZE5MTHM5RHlpY3dtdG8iLAogICAgICAgICAgICAiZW1haWwiOiJ1bnVzZWRAZXhhbXBsZS5jb20iLAogICAgICAgICAgICAiYXV0aCI6IloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMHlNalUxTXpJME9uWlZhMnRxV1dST1RFeHpPVVI1YVdOM2JYUnYiCiAgICAJfQogICAgfQp9